import type { Realm } from '@/src/features/game/types';
import { colors } from '@/src/theme';

export const REALMS: Realm[] = [
  {
    id: 'shadows',
    name: 'Shadows',
    epithet: 'Realm I — Privacy',
    tagline: 'Read the tell. Strike before the veil lifts.',
    accent: colors.violet,
    status: 'live',
    guardian: { name: 'Veilwarden', title: 'Guardian of Shadows', heldSince: '2d 4h', timeWeight: 1.4 },
    xp: 1240,
    xpThreshold: 2000,
    bypass: 'Detect 3 behavioral tells in a row to bypass the trial gate.',
    trials: [
      {
        id: 'shadow-match',
        realmId: 'shadows',
        title: 'Match the Actor',
        kind: 'Glance trial',
        prompt: 'Three actors move through the dark. One hesitates before every door. Who is the infiltrator?',
        options: ['The First', 'The Second', 'The Third'],
        answerIndex: 1,
        signal: 'Timing spread: 0.4s / 1.9s / 0.5s — the Second lingers.',
        probeSignal: 'Probe: the Second checks over its shoulder twice. Confidence up.',
      },
      {
        id: 'shadow-duel',
        realmId: 'shadows',
        title: 'Detector Duel',
        kind: 'Head-to-head',
        prompt: 'Your opponent masks their rhythm. Which pattern is a feint?',
        options: ['Fast-fast-slow', 'Slow-slow-fast', 'Even tread'],
        answerIndex: 0,
        signal: 'Opponent over-commits speed early — classic feint shape.',
        probeSignal: 'Probe: opponent glances at the timer on fast beats. Feint confirmed.',
      },
      {
        id: 'shadow-marker',
        realmId: 'shadows',
        title: 'Shadow Marker',
        kind: 'Location trial',
        prompt: 'A marker sleeps somewhere in the district. Which quarter hums?',
        options: ['North cistern', 'Glass market', 'Ashen steps'],
        answerIndex: 2,
        signal: 'Rarity spread: foot traffic thins near the Ashen steps.',
        probeSignal: 'Probe: cold draft + chalk dust at the steps. Marker near.',
      },
    ],
  },
  {
    id: 'flow',
    name: 'Flow',
    epithet: 'Realm II — Tokens',
    tagline: 'Find the best route before slippage finds you.',
    accent: colors.jade,
    status: 'sealed',
    guardian: { name: 'Unclaimed', title: 'Awaiting Guardian', heldSince: '—', timeWeight: 1.0 },
    xp: 0,
    xpThreshold: 2000,
    bypass: 'Route Master bypass: chain 3 optimal routes under pressure.',
    trials: [
      {
        id: 'flow-route',
        realmId: 'flow',
        title: 'Best Route',
        kind: 'Glance trial',
        prompt: 'Three routes quote the same swap. Which has the least price impact?',
        options: ['Route A · −1.8%', 'Route B · −0.6%', 'Route C · −2.4%'],
        answerIndex: 1,
        signal: 'Impact estimates shown free. Depth favors Route B.',
        probeSignal: 'Probe: Route A hides a thin pool mid-hop. B holds.',
      },
    ],
  },
  {
    id: 'artifacts',
    name: 'Artifacts',
    epithet: 'Realm III — Relics',
    tagline: 'Separate the real from the counterfeit.',
    accent: colors.gold,
    status: 'sealed',
    guardian: { name: 'Unclaimed', title: 'Awaiting Guardian', heldSince: '—', timeWeight: 1.0 },
    xp: 0,
    xpThreshold: 2000,
    bypass: 'Keen Eye bypass: call 3 fakes in a row.',
    trials: [
      {
        id: 'artifact-rarity',
        realmId: 'artifacts',
        title: 'Rarest Trait',
        kind: 'Glance trial',
        prompt: 'Trait spread across the collection. Which trait is rarest?',
        options: ['Obsidian halo · 4.1%', 'Ember sigil · 0.7%', 'FrostBrand · 2.2%'],
        answerIndex: 1,
        signal: 'Distribution shown free. Ember sigil is thinnest.',
        probeSignal: 'Probe: wash-trading inflates halo counts. Sigil holds.',
      },
    ],
  },
];
